name: 'Build Docker images'

on:
  push:
    branches: [main]

env:
  STABLE_VERSION: '2.25'
  LATEST_VERSION: '2.26'
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-image:
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        version: ['2.26', '2.25']
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ${{ matrix.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Extract Docker metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=false
      - name: Build and push Docker image (latest)
        if: ${{ matrix.version == env.LATEST_VERSION }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_VERSION }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
      - name: Build and push Docker image (stable)
        if: ${{ matrix.version == env.STABLE_VERSION }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.version }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:stable,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.STABLE_VERSION }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
